[package]
name = "parqbench"
version = "0.1.2"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Connor Keane <connor.keane@kxnr.me"]
rust-version = "1.62"
description = "A utility for viewing parquet files built on egui."

[dependencies]
egui = "~0.19"
egui_extras = "~0.19"
eframe = { version = "~0.19", features = ["persistence"] }
datafusion = "12.0.0"
rfd = { version ="~0.10", features = ["file-handle-inner"] }
tokio = { version = "1.21.1", features = ["rt", "sync"] }
tracing-subscriber = "0.3"

[features]
default = []

[profile.release]
opt-level = 2
