[package]
name = "parqbench"
version = "0.2.1"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Connor Keane <connor.keane@kxnr.me"]
rust-version = "1.64"
description = "A utility for viewing parquet files built on egui."

[dependencies]
egui = "~0.19"
egui_extras = "~0.19"
eframe = { version = "~0.19", features = ["persistence"] }
datafusion = "~8"
rfd = { version ="~0.10", features = ["file-handle-inner"] }
tokio = { version = "1.21.1", features = ["rt", "sync"] }
tracing-subscriber = "0.3"
structopt = "~0.3"
shellexpand = "~2"
parquet = "~23.0"

[features]
default = []

[profile.release]
opt-level = 2
