[package]
name = "parqbench"
version = "0.2.2"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Connor Keane <connor.keane@kxnr.me"]
rust-version = "1.75"
description = "A utility for viewing parquet files built on egui."

[dependencies]
egui = "~0.19"
egui_extras = "~0.19"
eframe = { version = "~0.19", features = ["persistence"] }
datafusion = "~8"
rfd = { version ="~0.10", features = ["file-handle-inner"] }
tokio = { version = "1.21.1", features = ["rt", "sync"] }
tracing-subscriber = "0.3"
structopt = "~0.3"
shellexpand = "*"
parquet = "*"

[features]
default = []

[profile.release]
# https://doc.rust-lang.org/cargo/reference/profiles.html
debug = false           # No debug info at all.
strip = "symbols"       # Strip symbols from a binary.
opt-level = 3           # All optimizations.
overflow-checks = true  # Panic will occur on overflow.
lto = true              # Enable link time optimization.
codegen-units = 1       # Use a single codegen for size optimization.
panic = "abort"         # Remove traceback information.
incremental = true      # Save information to disk, improving re-compile times.

[profile.dev]
opt-level = 1       