[package]
name = "parqbench"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Connor Keane <connor.keane@kxnr.me"]
rust-version = "1.60"
description = "A utility for viewing parquet files built on egui."

[dependencies]
egui = "~0.18"
egui_extras = "~0.18"
eframe = { version = "~0.18", features = ["persistence"] }
datafusion = "~8"
rfd = { version ="~0.8", features = ["file-handle-inner"] }
tokio = { version = "~1.19", features = ["rt", "sync"] }
tracing-subscriber = "0.3"

[features]
default = []

[profile.release]
opt-level = 2
