[package]
name = "parqbench"
version = "0.1.0"
edition = "2021"
authors = ["Connor Keane <connor.keane@kxnr.me"]
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.18.0"
egui_extras = "0.18.0"
eframe = { version = "0.18.0", features = ["persistence"] }
datafusion = "~7"
native-dialog = "0.6.3"
tokio = "~1"

[features]
default = []

[profile.release]
opt-level = 2 # fast and small wasm

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"